"""empty message

Revision ID: 622ab48cccd8
Revises: None
Create Date: 2015-12-19 21:46:36.076388

"""

# revision identifiers, used by Alembic.
revision = '622ab48cccd8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('galleries')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'users.id'], name=u'galleries_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'galleries_pkey')
    )
    op.drop_table('albums')
    ### end Alembic commands ###
